@extends('layouts.app')
@section('content')

    <div class="row page-titles">
        <div class="col-md-5 col-8 align-self-center">
            <h3 class="text-themecolor m-b-0 m-t-0">Voting</h3>
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="javascript:void(0)">Home</a></li>
                <li class="breadcrumb-item active">New Voting</li>
            </ol>
        </div>
        <div class="col-md-7 col-4 align-self-center">
            <div class="d-flex m-t-10 justify-content-end">
                <div class="d-flex m-r-20 m-l-10 hidden-md-down">
                    <div class="chart-text m-r-10">
                        <h6 class="m-b-0"><small>THIS MONTH</small></h6>
                        <h4 class="m-t-0 text-info">$58,356</h4></div>
                    <div class="spark-chart">
                        <div id="monthchart"></div>
                    </div>
                </div>
                <div class="d-flex m-r-20 m-l-10 hidden-md-down">
                    <div class="chart-text m-r-10">
                        <h6 class="m-b-0"><small>LAST MONTH</small></h6>
                        <h4 class="m-t-0 text-primary">$48,356</h4></div>
                    <div class="spark-chart">
                        <div id="lastmonthchart"></div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- ============================================================== -->
    <!-- End Bread crumb and right sidebar toggle -->
    <!-- ============================================================== -->
    <!-- ============================================================== -->
    <!-- Start Page Content -->
    <!-- ============================================================== -->
    <div class="row">
        <div class="col-md-8">
            <div class="card">
                <div class="card-body text-dark">
                    <h4 class="card-title">All Tokens</h4>
                    <div class="table-responsive m-t-40">
                        <table id="example23" class="nowrap table  table-striped " cellspacing="0" width="100%">
                            <thead>
                            <tr>
                                <th>Token No.</th>
                                <th>Index No.</th>
                                <th>Department</th>
                                <th>Voting</th>
                                <th>Generated By</th>
                                <th>Manage</th>
                            </tr>
                            </thead>
                            <tbody>
                            {{--@foreach($voting as $vote)
                                <tr>
                                    <td>{{$vote->name}}</td>
                                    <td>{{$vote->department->name}}</td>
                                    <td>{{substr($vote->voting_date_start_time,0,10)}}</td>
                                    <td>{{substr($vote->voting_date_start_time,10)}}</td>
                                    <td>{{$vote->ending_time}}</td>
                                    <td>Detail</td>
                                    <td>
                                        @if(substr($vote->voting_date_start_time,0,10) <= \Carbon\Carbon::yesterday()->format('Y-m-d'))
                                            <label class="badge badge-danger">Ended</label>
                                        @elseif(substr($vote->voting_date_start_time,0,10) == \Carbon\Carbon::tomorrow()->format('Y-m-d'))
                                            <label class="badge badge-warning">Start Tomorrow</label>
                                        @elseif(strtotime(\Carbon\Carbon::now()->format('Y-m-d h:i A')) >= strtotime($vote->voting_date_start_time) && strtotime(\Carbon\Carbon::now()->format('h:i A')) < strtotime($vote->ending_time))
                                            <label class="badge badge-success">Ongoing</label>

                                        @elseif(strtotime(\Carbon\Carbon::now()->format('Y-m-d h:i A')) >= strtotime($vote->voting_date_start_time) && strtotime(\Carbon\Carbon::now()->format('h:i A')) >= strtotime($vote->ending_time))
                                            <label class="badge badge-danger">Ended</label>
                                        @endif
                                    </td>
                                    <td>
                                        <a class="" href="#">Result</a>
                                    </td>
                                    <td>
                                        <div class="dropdown">
                                            <button class="btn btn-secondary btn-sm dropdown-toggle" type="button" id="manage" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                                Action
                                            </button>
                                            <div class="dropdown-menu" aria-labelledby="manage">
                                                <a href="{{route('voting.edit',$vote->id)}}" class="dropdown-item ml-1 text-dark">
                                                    <i class="mdi mdi-account-edit"></i> Edit
                                                </a>
                                                <a class="dropdown-item" href="#">
                                                    <form method="post" action="{{route('voting.destroy',$vote->id)}}" onsubmit="return confirm('Do you really want to delete this Voting')">
                                                        @csrf
                                                        {!! method_field('DELETE') !!}
                                                        <button type="submit" style="background: transparent; border: 0;">
                                                            <i class="mdi mdi-delete"></i> Delete
                                                        </button>
                                                    </form>
                                                </a>

                                                <a class="dropdown-item" href="#">
                                                    <form method="post" action="{{route('startOrEndVoting',$vote->id)}}" onsubmit="return confirm('Are you sure you want to continue?')">
                                                        @csrf
                                                        <button type="submit" style="background: transparent; border: 0;">
                                                            @if($vote->status == 0)
                                                                <i class="mdi mdi-power-plug"></i> Start Voting
                                                            @else
                                                                <i class="mdi mdi-power-plug-off"></i> End Voting
                                                            @endif
                                                        </button>
                                                    </form>
                                                </a>
                                            </div>
                                        </div>
                                    </td>
                                </tr>
                            @endforeach--}}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>

        <div class="col-md-4">
            <div class="card">
                <div class="card-body">
                    <h4 class="card-title">New Token</h4>
                    <form class="m-t-40 needs-validation form-material" method="post" action="{{route('nominee_token.store')}}" novalidate>
                        @csrf
                        <div class="form-row">
                            <div class="col-md-12 mb-3 form-group">
                                <select name="voting_id" class="select2 form-control" required>
                                    <option value="">Select Voting</option>
                                    @foreach($voting as $vote)
                                        <option value="{{$vote->id}}">{{$vote->name}}</option>
                                    @endforeach
                                </select>
                                <div class="invalid-feedback">
                                    Voting required!
                                </div>
                            </div>

                            <div class="col-md-12 mb-3 form-group">
                                <select name="department_id" class="select2 form-control"required>
                                    <option value="">Select Department</option>
                                    @foreach($departments as $department)
                                        <option value="{{$department->id}}">{{$department->name}}</option>
                                    @endforeach
                                </select>
                                <div class="invalid-feedback">
                                    Department required!
                                </div>
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="form-row">
                                <div class="col-md-12 mb-3">
                                    <input type="text" class="form-control" name="index_number" id="validationCustom01" placeholder="Index Number" required>
                                    <div class="invalid-feedback">
                                        Index Number required
                                    </div>
                                </div>
                            </div>
                            <div class="form-row">
                                <div class="col-md-8">
                                    <input class="form-control" placeholder="Token" type="text" name="random_token" id="random_token">
                                    <div class="invalid-feedback">
                                        Index Number required
                                    </div>
                                </div>
                                <div class="col-md-4 mb-3">
                                    <button class="btn btn-info" type="button" id="generate_token">
                                        <i class="mdi mdi-key"> </i>
                                    </button>
                                    <script type="text/javascript">
                                        function random_password_generate(max,min)
                                        {
                                            var passwordChars = "0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ";
                                            var randPwLen = Math.floor(Math.random()) + min;
                                            return Array(randPwLen).fill(passwordChars).map(function (x) {
                                                return x[Math.floor(Math.random() * x.length)]
                                            }).join('');
                                        }
                                        document.getElementById("generate_token").addEventListener("click", function(){
                                            random_password = random_password_generate(16,8);
                                            document.getElementById("random_token").value = random_password;
                                        });
                                    </script>

                                </div>

                            </div>
                        </div>
                        <div class="text-xs-right">
                            <button type="submit" class="btn btn-info btn-block">Add Voter</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>

@endsection


